// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlLb4b4ErVzfZ-FigAhv01UEf9gxUCdfA',
    appId: '1:440841514188:web:333e39fc9381b9191fa669',
    messagingSenderId: '440841514188',
    projectId: 'mentorquiz-b3740',
    authDomain: 'mentorquiz-b3740.firebaseapp.com',
    storageBucket: 'mentorquiz-b3740.firebasestorage.app',
    measurementId: 'G-B245W547MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2n_-V8lJ3yjdST9pDArwmDsZE3HXlfgI',
    appId: '1:440841514188:android:d1554220fe4cf9d91fa669',
    messagingSenderId: '440841514188',
    projectId: 'mentorquiz-b3740',
    storageBucket: 'mentorquiz-b3740.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe61I2SzdkbWcdF4wMut2TeWTpHTZ8qU4',
    appId: '1:440841514188:ios:e269d44385eb0acc1fa669',
    messagingSenderId: '440841514188',
    projectId: 'mentorquiz-b3740',
    storageBucket: 'mentorquiz-b3740.firebasestorage.app',
    iosClientId: '440841514188-c1ibghttah8lkihp3tgf95mrade6vmn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentorQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe61I2SzdkbWcdF4wMut2TeWTpHTZ8qU4',
    appId: '1:440841514188:ios:e269d44385eb0acc1fa669',
    messagingSenderId: '440841514188',
    projectId: 'mentorquiz-b3740',
    storageBucket: 'mentorquiz-b3740.firebasestorage.app',
    iosClientId: '440841514188-c1ibghttah8lkihp3tgf95mrade6vmn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentorQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlLb4b4ErVzfZ-FigAhv01UEf9gxUCdfA',
    appId: '1:440841514188:web:720a838ac3e8892a1fa669',
    messagingSenderId: '440841514188',
    projectId: 'mentorquiz-b3740',
    authDomain: 'mentorquiz-b3740.firebaseapp.com',
    storageBucket: 'mentorquiz-b3740.firebasestorage.app',
    measurementId: 'G-JJE5RMVCPD',
  );
}
